server:
  port: 8082
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/scaffold"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "steiner"
    password: "mysql30449030"
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: "iot.technology"
  issuer: "scaffold"
  audience: "web"

open:
  urls:
    - "/authenticate"
  roles:
    - "student"
    - "admin"