server:
  port: 8082
  servlet:
    context-path: "/api"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/scaffold"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "steiner"
    password: "mysql30449030"
  exposed:
    generate-ddl: true
    show-sql: true

jwt:
  secret: "iot.technology"
  issuer: "scaffold"
  audience: "web"

open:
  urls:
    - "/authenticate"
  roles:
    - "student"
    - "admin"